# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'homeW1-2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


pod 'Alamofire', '~> 4.8'

pod 'SwiftyJSON', '~> 4.0'

pod 'Kingfisher', '~> 6.0'
pod 'RealmSwift'


  # Pods for homeW1-2

end

